trainer:
  output_dir: "outputs/"
  per_device_train_batch_size: 64
  num_train_epochs: 1
  gradient_accumulation_steps: 16
  gradient_checkpointing: True
  gradient_checkpointing_kwargs: {"use_reentrant": False}
  learning_rate: 1.41e-5
  report_to: "none"
  remove_unused_columns: False
  optim: "adamw_torch"
  logging_steps: 500
  evaluation_strategy: "no"
  max_length: 512