trainer:
  output_dir: "outputs/"
  per_device_train_batch_size: 16
  num_train_epochs: 2
  gradient_checkpointing: True
  gradient_checkpointing_kwargs: {"use_reentrant": False}
  learning_rate: 2e-5
  report_to: "none"
  remove_unused_columns: False
  optim: "adamw_torch"
  logging_steps: 500
  max_length: 512
  load_best_model_at_end: True
  evaluation_strategy: 'steps'